services:
  web_proxy:
    image: nginx:alpine
    container_name: edge_proxy
    ports:
      - "80:80"
    networks:
      - frontend_net
      - backend_net

  db:
    image: mariadb:11
    container_name: internal_db
    environment:
      MYSQL_ROOT_PASSWORD: faithesofjeter
      MYSQL_DATABASE: appdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 852456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  db_data:
